### PR TITLE
Raw bit generator sampling

### PR DESCRIPTION
**Pull request by RomeshA**
### Description

The issue observed in #568 appears to be because `rng.random()` (to get a random float) is faster than `rng.integers()`. It's been suggested that this is because `random()` is a pure C call while `integers()` has some Python logic as well. In the test case noted by @cliffckerr the simple model runtime is dominated by the transmission portion of the calculation and this difference is big enough to provide a noticeable difference in runtime.

@daniel-klein had suggested a while ago that maybe we could just use the numpy bit generator directly to get the random integers we need. I've implemented this in a new `Dist`, `rand_uint64`,  that calls `bitgen.random_raw` to get the `uint64` array of random integers that is then passed to `combine_rands`. We're already asking users who want to use `combine_rands` to create `Dist` instances with integers even though the final random number is going to be a float, so they have to view the setup as an integrated package (with integer `Dists` and `combine_rands`) so I don't think it's too onerous (and in fact, maybe a bit simpler/clearer) to just say `rand_uint64` provides inputs for use with `combine_rands` (could potentially give it a better name).

Performance is a little bit tricky because the current `main` branch has had other optimizations in the meantime. Running @cliffckerr 's test script from #568 gives

- Old `main` (`43249e3`): 733 ms ± 3.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
- `combine_rands` (`4689698`): **10% slower** (810 ms ± 6.61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each))
- `main` (`4e0bcfc`): **12% faster** (641 ms ± 15.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each))
- `test_raw_rng`: **20% faster** (582 ms ± 4.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each))

So overall `test_raw_rng` has higher performance than the old `main` branch where `combine_rands` had worse performance. The impact of this issue depends on what proportion of time in a model is spent calculating transmission, so for a complex model like STIsim, it makes almost no difference to the runtime because so much time is spent on other parts of the model). 

Not sure about whether it's worth the added complexity of a separate integer generator just for this purpose, but on the other hand, the performance _is_ better and it solves #568, so opening this PR for comment/review

### Checklist
- [ ] Code commented & docstrings added
- [ ] New tests were needed and have been added
- [ ] A new version number was needed & changelog has been updated
- [ ] A new PyPI version needs to be released

### CODE REVIEW

**Comment by daniel-klein** [comment]
Thanks @RomeshA, this looks amazing. I saw the `random_raw` as well, but at that point was convinced that we needed signed integers. In response to your comment on the paper, I've done a bit more archeology and no longer see an advantage either way.

**Review by daniel-klein — APPROVED** [review]
Looks good! I just added a fix to enable `_centralized`, which I'm using for the CRN paper. Also just running a statistical test (from the paper) to make sure all is well, but assuming it will be fine.

**Comment by daniel-klein** [comment]
Ut oh! Just ran a small test and it seems to produce highly biased results. Need to do some more investigation, but please do not merge yet!

image

**Review by daniel-klein — CHANGES_REQUESTED** [review]
Trying to remove my "approval" due to the observed bias.

**Comment by RomeshA** [comment]
@daniel-klein Weird! It looked fine with Cliff's 2D histogram tests, and a reduced run of `explore_tx_correlation.py` also seemed OK - what was the script that produced those biased results?

**Comment by daniel-klein** [comment]
@RomeshA https://github.com/starsimhub/crn_paper/blob/main/explore_erdosrenyinet.py

**Comment by daniel-klein** [comment]
I'm wondering if it's related to this warning in the [random_raw](https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.random_raw.html) documentation:
```
This method directly exposes the raw underlying pseudo-random number generator. All values are returned as unsigned 64-bit values irrespective of the number of bits produced by the PRNG.
```

For the failing test, I'm using the default Mersenne Twister.

**Comment by daniel-klein** [comment]
Ah yes, that's probably it. From the [Mersenne Twister (MT19937)](https://numpy.org/doc/stable/reference/random/bit_generators/mt19937.html) docs:
```
The [MT19937](https://numpy.org/doc/stable/reference/random/bit_generators/mt19937.html#numpy.random.MT19937) state vector consists of a 624-element array of 32-bit unsigned integers plus a single integer value between 0 and 624 that indexes the current position within the main array.
```

**Comment by daniel-klein** [comment]
Let me try with a different Generator

**Comment by daniel-klein** [comment]
"The [PCG64DXSM](https://numpy.org/doc/stable/reference/random/bit_generators/pcg64dxsm.html#numpy.random.PCG64DXSM) state vector consists of 2 unsigned 128-bit values, which are represented externally as Python ints."

Not sure how well this will work, might just be inefficient to return as `uint64`, but running test now.

**Comment by daniel-klein** [comment]
Yay, all good with PCG64DXSM. I can fix `_centralized` with something like the following
```python
np.random.mtrand._rand.randint(low=0, high=np.iinfo(np.uint64).max, dtype=np.uint64, size=n)
```

**Review by daniel-klein — APPROVED** [review]
So it depends on the Generator, with PCG-64 DXSM (our default) being okay but Mersenne Twister (MT19937) no good. Have created a workaround for `_centralized`.

**Comment by RomeshA** [comment]
Great, thanks for looking into that @daniel-klein !

**Pull request merged**
