### PR TITLE
Net chunking

### PR DESCRIPTION
**Pull request by daniel-klein**
### Description

Adding chunking to ErdosRenyiNet. Chunking trades memory for CPU, allowing the algorithm to run on larger networks, but at the cost of additional wall clock time.

NOTE: Redundancy in the chunking algorithm between ErdosRenyiNet and DiskNet that should be improved.

### Checklist
- [ ] Code commented & docstrings added
- [ ] New tests were needed and have been added
- [ ] A new version number was needed & changelog has been updated
- [ ] A new PyPI version needs to be released

### CODE REVIEW

**Comment by daniel-klein** [comment]
Note also includes changes from #595

**Comment by cliffckerr** [comment]
I would prefer the O(N) algorithm if that's acceptable (it's not strictly identical to an E-R network, but should be close enough for all practical purposes).

**Review by cliffckerr — COMMENTED** [review]
I would prefer the O(N) algorithm if that's acceptable (it's not strictly identical to an E-R network, but should be close enough for all practical purposes).

**Comment by cliffckerr** [comment]
Going to close this for now, but will leave the branch and we can revisit post-Symposium.

**Pull request closed without merging**
