### PR TITLE
Add pull request template

### LINKED ISSUE #471: Add pull request template
Add checklist as reminder to update version and changelog

### PR DESCRIPTION
**Pull request by cliffckerr**
### Description
Adds PR template, closes #471

### Checklist
- [ ] Code commented & docstrings added
- [ ] New tests were needed and have been added
- [ ] A new version number is needed & changelog has been updated
- [ ] A new PyPI version needs to be released

### CODE REVIEW

**Review by kaa2102 — APPROVED** [review]
Good to go!

**Comment by RomeshA** [comment]
For a checklist is the idea that all of the items are checked off as a prerequisite for merging? That would make it easy to quickly see that everything had been covered. In that case, something like "New tests were needed and have been added" could instead be "New tests not required OR relevant tests have been added" (or similar) so that way a user that didn't need new tests would still check the box. Same with the new version number e.g. "Version number has been incremented and changelog updated OR new version number not required"

**Comment by kaa2102** [comment]
> For a checklist is the idea that all of the items are checked off as a prerequisite for merging? That would make it easy to quickly see that everything had been covered. In that case, something like "New tests were needed and have been added" could instead be "New tests not required OR relevant tests have been added" (or similar) so that way a user that didn't need new tests would still check the box. Same with the new version number e.g. "Version number has been incremented and changelog updated OR new version number not required"

I agree with this sentiment. In discussions, I mentioned that version and changelog updates may be required after a significant change or 4-5 merges. The checkbox option @RomeshA mentioned should be available.

**Comment by cliffckerr** [comment]
I went back and forth on this (as you can see from the commit history!), but decided on this approach because I didn't want it to be a, well, box-ticking exercise! I assume that when making the PR, having the boxes be there will be enough of a reminder to the PR author. And then during PR review, I thought _not_ having all the boxes necessarily ticked would be more informative for the reviewer (e.g. whether they agree with the author that new tests aren't required). But happy to revert to the "added or not needed" version if everyone prefers that!

**Pull request merged**
