### PR TITLE
timestep enum

### PR DESCRIPTION
**Pull request by menriquez-IDM**
### Description
A suggestion for starsim, it could be a useful feature to have for the users. Why I put it in a folder, because the idea is to have the same level of information, samples etc. for other enums which may come along. 
Feedback and other considerations are welcome. 

### Checklist
- [x] Code commented & docstrings added
- [x] New tests were needed and have been added
- [ ] A new version number was needed & changelog has been updated
- [ ] A new PyPI version needs to be released

Not sure if it's worth to have a new version.

### CODE REVIEW

**Comment by menriquez-IDM** [comment]
@JSchripsema-IDM  this is a case where the preview documents Github action actually help :)  ... or is there a way to see why it failed?

**Comment by JSchripsema-IDM** [comment]
@menriquez-IDM clicking "Details" should show you the build logs on RTD:

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/institute-for-disease-modeling-starsim/envs/610/lib/python3.11/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/institute-for-disease-modeling-starsim/checkouts/610/docs/conf.py", line 8, in <module>
    import starsim as ss
  File "/home/docs/checkouts/readthedocs.org/user_builds/institute-for-disease-modeling-starsim/envs/610/lib/python3.11/site-packages/starsim/__init__.py", line 21, in <module>
    from .enums.timestep  import TimeStep
ModuleNotFoundError: No module named 'starsim.enums'

**Comment by menriquez-IDM** [comment]
I tried that however I get a 404, am I missing something? 
In any case, thanks for investigating for me.

**Comment by cliffckerr** [comment]
I think the issue is with the subfolder. You could try adding an `__init__.py` file to the subfolder, or just move the file to the main folder.

However, the time refactor will mean that a year is no longer fixed as the base time unit, so we shouldn't need a enum for this. We have discussed having an `EnumArr` (https://github.com/starsimhub/starsim/issues/609), but we'll revisit that after v2.0.

**Pull request closed without merging**
