### PR TITLE
Ongoing changes to fix bugs and improve features

### PR DESCRIPTION
**Pull request by daniel-klein**
### Description

* Reworked calibration interface
* Adds pregnancy burnin
* Adds `min_slots` simulation parameter
* Ensures infertile and non-fecund agents do not give birth
* Moves `update_death ` from disease to module, and uses it for Pregnancy
* Adds a gamma distribution
* Adds a `parent` state to each agent
* Adds `child_uids` to pregnant and postpartum women

### Checklist
- [ ] Code commented & docstrings added
- [ ] New tests were needed and have been added
- [ ] A new version number was needed & changelog has been updated
- [ ] A new PyPI version needs to be released

### CODE REVIEW

**Comment by daniel-klein** [comment]
Sorry, this is based on a slightly older main - might be a chore to merge!

**Comment by daniel-klein** [comment]
I didn't bump version or perform tests either, will do that now!

**Comment by cliffckerr** [comment]
Ooh, yikes ... yes, this looks like it could be a lot of merge conflicts!

**Comment by cliffckerr** [comment]
Would be nice to have these changes in, after `rethink-time` is merged into `rc2.0`, would it be feasible to resolve the merge conflicts merge these in as well this week?

**Comment by daniel-klein** [comment]
Replaced by #655

**Pull request closed without merging**
